### PR TITLE
chore: change name of community Flux module

### PR DESCRIPTION
**Pull request by wolffcm**
This commit updates this fork of Flux to be separate from the [InfluxData-maintained fork](https://github.com/influxdata/flux), for use and development by interested community members.

I updated the `go.mod` file and import paths in Go source code to reflect the org name `InfluxCommunity`, and made a few other changes to generated files, etc so that everything works right. Client code using the InfluxData fork can switch to using this one by importing `github.com/InfluxCommunity/flux`, but otherwise, everything should be the same.

Of note:

> I had to [update](https://github.com/influxdata/pkg-config/pull/42) our special version of [`pkg-config`](https://github.com/influxdata/pkg-config) so that builds would work with both forks.

One outstanding item here is that CI needs to be set up. InfluxData uses Quay to host Docker images and CircleCI for continuous integration. Some other solution will be needed moving forward here.

### CODE REVIEW

**Comment by lmangani** [comment]
Awesome @wolffcm!  In order to fully test/validate I think we also need a release/tag as well for go mod builders to import the new Flux sources?

**Comment by wolffcm** [comment]
@lmangani How about I merge this, and then we tag it with a version number? We could give it the same version number of the current InfluxData Flux (`v0.194.3`), or start fresh? I think this could affect you moving forward, so I'll let you decide.

**Comment by lmangani** [comment]
@wolffcm sounds like a plan!

**Review by lmangani — APPROVED** [review]

**Comment by lmangani** [comment]
Note: we'll need issues enabled for this repository. Any chance you could enable it?

**Comment by wolffcm** [comment]
@lmangani Sure, I've enabled issues. 

I think if you tag the latest commit with a version like `v0.194.3` you should be able to import it into your projects. I'm curious to see how that goes.

**Comment by lmangani** [comment]
Tagged, rebuilt Fluxpipe from this repo, and all is looking good! https://github.com/metrico/fluXpipe/releases/tag/v0.194.6
Will do some more experiments but I'd call this a full success @wolffcm 🥳

**Pull request merged**
